AttributeError: module 'cv2.cv2' has no attribute 'aruco'
False: Non-zero return code, probably a syntax error occurred\ntime=1606299761.2962437 gym-duckietown 2019.0.0

time=1606299761.52 Registering gym environment id: Duckietown-4way-v0
time=1606299761.5201776 Registering gym environment id: Duckietown-loop_dyn_duckiebots-v0
time=1606299761.520283 Registering gym environment id: Duckietown-loop_empty-v0
time=1606299761.5204122 Registering gym environment id: Duckietown-loop_obstacles-v0
time=1606299761.5205271 Registering gym environment id: Duckietown-loop_pedestrians-v0
time=1606299761.5206494 Registering gym environment id: Duckietown-small_loop-v0
time=1606299761.5207644 Registering gym environment id: Duckietown-small_loop_cw-v0
time=1606299761.5208924 Registering gym environment id: Duckietown-straight_road-v0
time=1606299761.5210185 Registering gym environment id: Duckietown-straight_road_10_tiles_no_start_tile-v0
time=1606299761.521233 Registering gym environment id: Duckietown-straight_road_no_start_tile-v0
time=1606299761.5213668 Registering gym environment id: Duckietown-straight_road_trafficlight-v0
time=1606299761.5214932 Registering gym environment id: Duckietown-straight_road_with_side_floor-v0
time=1606299761.521618 Registering gym environment id: Duckietown-udem1-v0
time=1606299761.5217156 Registering gym environment id: Duckietown-zigzag_dists-v0
[ WARN:0] global /tmp/pip-req-build-qacpj5ci/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/appuser/aido-auto/gym-duckietown/gym_duckietown/tasks/lf_challenge/checker.py", line 6, in <module>
    checkers=[RewardChecker()]
  File "/home/appuser/aido-auto/gym-duckietown/gym_duckietown/tasks/solution_evaluator.py", line 31, in __init__
    solution_file_as_module = importlib.import_module(self.args.solution_file_as_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/appuser/aido-auto/gym-duckietown/gym_duckietown/tasks/lf_challenge/solutions/solution.py", line 10, in <module>
    class DontCrushDuckieTaskSolution(TaskSolution):
  File "/home/appuser/aido-auto/gym-duckietown/gym_duckietown/tasks/lf_challenge/solutions/solution.py", line 24, in DontCrushDuckieTaskSolution
    dictionary=cv2.aruco.Dictionary_get(cv2.aruco.DICT_6X6_250)
AttributeError: module 'cv2.cv2' has no attribute 'aruco'
