numpy.AxisError: axis 2 is out of bounds for array of dimension 0
False: Non-zero return code, probably a syntax error occurred\ntime=1606748368.3511677 gym-duckietown 2019.0.0

time=1606748368.6090937 Registering gym environment id: Duckietown-4way-v0
time=1606748368.6092706 Registering gym environment id: Duckietown-loop_dyn_duckiebots-v0
time=1606748368.6093745 Registering gym environment id: Duckietown-loop_empty-v0
time=1606748368.6094542 Registering gym environment id: Duckietown-loop_obstacles-v0
time=1606748368.6095273 Registering gym environment id: Duckietown-loop_pedestrians-v0
time=1606748368.6096034 Registering gym environment id: Duckietown-small_loop-v0
time=1606748368.609678 Registering gym environment id: Duckietown-small_loop_cw-v0
time=1606748368.609798 Registering gym environment id: Duckietown-straight_road-v0
time=1606748368.6099107 Registering gym environment id: Duckietown-straight_road_10_tiles_no_start_tile-v0
time=1606748368.6101236 Registering gym environment id: Duckietown-straight_road_no_start_tile-v0
time=1606748368.6102338 Registering gym environment id: Duckietown-straight_road_trafficlight-v0
time=1606748368.6103146 Registering gym environment id: Duckietown-straight_road_with_side_floor-v0
time=1606748368.6103761 Registering gym environment id: Duckietown-udem1-v0
time=1606748368.6105494 Registering gym environment id: Duckietown-zigzag_dists-v0
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/appuser/aido-auto/gym-duckietown/gym_duckietown/tasks/lf_challenge/checker.py", line 6, in <module>
    checkers=[RewardChecker()]
  File "/home/appuser/aido-auto/gym-duckietown/gym_duckietown/tasks/solution_evaluator.py", line 31, in __init__
    solution_file_as_module = importlib.import_module(self.args.solution_file_as_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/appuser/aido-auto/gym-duckietown/gym_duckietown/tasks/lf_challenge/solutions/solution.py", line 20, in <module>
    wi = white_mask(bgr)
  File "/home/appuser/aido-auto/gym-duckietown/gym_duckietown/tasks/lf_challenge/solutions/solution.py", line 7, in white_mask
    ln = np.mean(bgr, axis=2) > 60
  File "<__array_function__ internals>", line 6, in mean
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 3373, in mean
    out=out, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py", line 147, in _mean
    rcount = _count_reduce_items(arr, axis)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py", line 66, in _count_reduce_items
    items *= arr.shape[mu.normalize_axis_index(ax, arr.ndim)]
numpy.AxisError: axis 2 is out of bounds for array of dimension 0
